export type Stat = [StatId, number];

export type StatMapBuilder = <I extends IntermediateConfig>(
  _: I,
) => Stat[];

export enum MainWeaponTypeId {
  BARE_HAND,
  ONE_HANDED_SWORD,
  TWO_HANDED_SWORD,
  BOW,
  BOWGUN,
  STAFF,
  MAGIC_DEVICE,
  KNUCKLES,
  HALBERD,
  KATANA,
}

export enum SubWeaponTypeId {
  NONE,
  KATANA,
  ONE_HANDED_SWORD,
  MAGIC_DEVICE,
  DAGGER,
  SHIELD,
  NINJUTSU_SCROLL,
  ARROW,
  KNUCKLES,
}

export enum StatId {
  FLAT_STR,
  PERCENT_STR,

  FLAT_INT,
  PERCENT_INT,

  FLAT_DEX,
  PERCENT_DEX,

  FLAT_VIT,
  PERCENT_VIT,

  FLAT_AGI,
  PERCENT_AGI,

  FLAT_WEAPON_ATK,
  PERCENT_WEAPON_ATK,

  FLAT_MATK,
  PERCENT_MATK,

  FLAT_ATK,
  PERCENT_ATK,

  FLAT_ASPD,
  PERCENT_ASPD,

  FLAT_CSPD,
  PERCENT_CSPD,

  FLAT_CRITICAL_RATE,
  PERCENT_CRITICAL_RATE,

  FLAT_CRITICAL_DAMAGE,
  PERCENT_CRITICAL_DAMAGE,

  FLAT_MAX_HP,
  PERCENT_MAX_HP,

  FLAT_MAX_MP,
  PERCENT_MAX_MP,

  FLAT_ACCURACY,
  PERCENT_ACCURACY,

  FLAT_DODGE,
  PERCENT_DODGE,

  FLAT_DEF,
  PERCENT_DEF,

  FLAT_MDEF,
  PERCENT_MDEF,

  FLAT_UNSHEATHE_ATTACK,
  PERCENT_UNSHEATHE_ATTACK,

  FLAT_ATTACK_MP_RECOVERY,
  PERCENT_ATTACK_MP_RECOVERY,

  FLAT_NATURAL_HP_REGEN,
  PERCENT_NATURAL_HP_REGEN,
  FLAT_NATURAL_MP_REGEN,
  PERCENT_NATURAL_MP_REGEN,

  STABILITY,

  MAGIC_PIERCE,
  PHYSICAL_PIERCE,

  LONG_RANGE_DAMAGE,
  SHORT_RANGE_DAMAGE,

  MOTION_SPEED,

  ATK_UP_STR,
  ATK_UP_INT,
  ATK_UP_DEX,
  ATK_UP_VIT,
  ATK_UP_AGI,

  MATK_UP_STR,
  MATK_UP_INT,
  MATK_UP_DEX,
  MATK_UP_VIT,
  MATK_UP_AGI,

  ATK_DOWN_STR,
  ATK_DOWN_INT,
  ATK_DOWN_DEX,
  ATK_DOWN_VIT,
  ATK_DOWN_AGI,

  MATK_DOWN_STR,
  MATK_DOWN_INT,
  MATK_DOWN_DEX,
  MATK_DOWN_VIT,
  MATK_DOWN_AGI,

  MAGIC_RESISTANCE,
  PHYSICAL_RESISTANCE,

  LIGHT_RESISTANCE,
  DARK_RESISTANCE,

  FIRE_RESISTANCE,
  WATER_RESISTANCE,
  EARTH_RESISTANCE,
  WIND_RESISTANCE,

  NEUTRAL_RESISTANCE,
  AILMENT_RESISTANCE,

  DAMAGE_TO_DARK,
  DAMAGE_TO_LIGHT,
  DAMAGE_TO_EARTH,
  DAMAGE_TO_WATER,
  DAMAGE_TO_FIRE,
  DAMAGE_TO_WIND,

  AGGRO,

  TUMBLE_UNAVAILABLE,
  FLINCH_UNAVAILABLE,
  STUN_UNAVAILABLE,

  DARK_ELEMENT,
  LIGHT_ELEMENT,
  EARTH_ELEMENT,
  WATER_ELEMENT,
  FIRE_ELEMENT,
  WIND_ELEMENT,

  GUARD_POWER,
  GUARD_RECHARGE,
  GUARD_BREAK,

  EVASION_RECHARGE,
  ANTICIPATE,

  ITEM_COOLDOWN,
  INVINCIBLE_AID,

  ABSOLUTE_ACCURACY,
  ABSOLUTE_DODGE,

  PHYSICAL_BARRIER,
  MAGIC_BARRIER,
  FRACTIONAL_BARRIER,
  BARRIER_COOLDOWN,

  ADDITIONAL_MELEE,
  ADDITIONAL_MAGIC,
}

export enum PersonalStatId {
  CRT,
  LUK,
  TEC,
  MTL,
  NONE,
}

export enum ArmorTypeId {
  LIGHT,
  HEAVY,
  NORMAL,
  NONE,
}

export enum ElementType {
  DARK,
  LIGHT,
  EARTH,
  WATER,
  FIRE,
  WIND,
}

export enum ResonanceSetId {
  MATK_AND_ATK,
  ACC_AND_CRIT,
  ASPD_AND_CSPD,
}

export enum ParamId {
  CHARACTER_LEVEL,

  CHARACTER_BASE_STR,
  CHARACTER_BASE_INT,
  CHARACTER_BASE_DEX,
  CHARACTER_BASE_VIT,
  CHARACTER_BASE_AGI,

  CHARACTER_PERSONAL_STAT_ID,
  CHARACTER_PERSONAL_STAT_VALUE,

  CHARACTER_MAINWEAPON_TYPE,
  CHARACTER_MAINWEAPON_ATK,
  CHARACTER_MAINWEAPON_REFINEMENT,
  CHARACTER_MAINWEAPON_STABILITY,
  CHARACTER_MAINWEAPON_STATMAP,
  CHARACTER_MAINWEAPON_CRYSTAL1_STATMAP,
  CHARACTER_MAINWEAPON_CRYSTAL2_STATMAP,

  CHARACTER_SUBWEAPON_TYPE,
  CHARACTER_SUBWEAPON_ATK,
  CHARACTER_SUBWEAPON_DEF,
  CHARACTER_SUBWEAPON_REFINEMENT,
  CHARACTER_SUBWEAPON_STABILITY,
  CHARACTER_SUBWEAPON_STATMAP,
  CHARACTER_SUBWEAPON_CRYSTAL1_STATMAP,
  CHARACTER_SUBWEAPON_CRYSTAL2_STATMAP,
  CHARACTER_SUBWEAPON_SCROLL_CAST_TIME_REDUCTION,
  CHARACTER_SUBWEAPON_SCROLL_MP_REDUCTION,

  CHARACTER_ARMOR_DEF,
  CHARACTER_ARMOR_REFINEMENT,
  CHARACTER_ARMOR_TYPE,
  CHARACTER_ARMOR_STATMAP,
  CHARACTER_ARMOR_CRYSTAL1_STATMAP,
  CHARACTER_ARMOR_CRYSTAL2_STATMAP,

  CHARACTER_ADDITIONAL_GEAR_DEF,
  CHARACTER_ADDITIONAL_GEAR_REFINEMENT,
  CHARACTER_ADDITIONAL_GEAR_STATMAP,
  CHARACTER_ADDITIONAL_GEAR_CRYSTAL1_STATMAP,
  CHARACTER_ADDITIONAL_GEAR_CRYSTAL2_STATMAP,

  CHARACTER_SPECIAL_GEAR_DEF,
  CHARACTER_SPECIAL_GEAR_STATMAP,
  CHARACTER_SPECIAL_GEAR_CRYSTAL1_STATMAP,
  CHARACTER_SPECIAL_GEAR_CRYSTAL2_STATMAP,

  CHARACTER_SKILLS_BLADESKILLS_HARDHIT_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_ASTUTE_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_TRIGGERSLASH_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_TRIGGERSLASH_ISACTIVE,
  CHARACTER_SKILLS_BLADESKILLS_RAMPAGE_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_RAMPAGE_ISACTIVE,
  CHARACTER_SKILLS_BLADESKILLS_METEORBREAKER_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_SHUTOUT_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_LUNARSLASH_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_SONICBLADE_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_SPIRALAIR_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_SWORDTEMPEST_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_BUSTERBLADE_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_BUSTERBLADE_ISACTIVE,
  CHARACTER_SKILLS_BLADESKILLS_AURABLADE_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_SWORDMASTERY_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_QUICKSLASH_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_SWORDTECHNIQUES_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_WARCRY_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_WARCRY_ISACTIVE,
  CHARACTER_SKILLS_BLADESKILLS_BERSERK_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_BERSERK_ISACTIVE,
  CHARACTER_SKILLS_BLADESKILLS_GLADIATE_LEVEL,
  CHARACTER_SKILLS_BLADESKILLS_SWIFTATTACK_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_POWERSHOT_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_BULLSEYE_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_ARROWRAIN_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_SNIPE_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_CROSSFIRE_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_VANQUISHER_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_TWINSTORM_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_TWINSTORM_ISACTIVE,
  CHARACTER_SKILLS_SHOTSKILLS_TWINSTORM_ONCOOLDOWN,
  CHARACTER_SKILLS_SHOTSKILLS_RETROGRADESHOT_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_MOEBASHOT_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_PARALYSISSHOT_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_SMOKEDUST_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_ARMBREAK_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_PARABOLACANNON_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_SHOTMASTERY_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_SAMURAIARCHERY_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_SAMURAIARCHERY_STACKS,
  CHARACTER_SKILLS_SHOTSKILLS_SNEAKATTACK_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_LONGRANGE_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_QUICKDRAW_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_DECOYSHOT_LEVEL,
  CHARACTER_SKILLS_SHOTSKILLS_FATALSHOT_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICARROWS_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICJAVELIN_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICLANCES_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICIMPACT_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICFINALE_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_CHRONOSSHIFT_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICWALL_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICBLAST_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICSTORM_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICBURST_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICCANNON_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICCRASH_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICMASTERY_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICKNIFE_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_QADAL_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_QADAL_BURDEN,
  CHARACTER_SKILLS_MAGICSKILLS_QADAL_ISACTIVE,
  CHARACTER_SKILLS_MAGICSKILLS_QADAL_COMBAT_TIME,
  CHARACTER_SKILLS_MAGICSKILLS_MPCHARGE_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_CHAINCAST_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_CHAINCAST_ISACTIVE,
  CHARACTER_SKILLS_MAGICSKILLS_CHAINCAST_STACKS,
  CHARACTER_SKILLS_MAGICSKILLS_POWERWAVE_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAXIMIZER_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_RAPIDCHARGE_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_RAPIDCHARGE_ISACTIVE,
  CHARACTER_SKILLS_MAGICSKILLS_RAPIDCHARGE_AMOUNTMPRECOVEREDFROMMAXIMIZER,
  CHARACTER_SKILLS_MAGICSKILLS_ENCHANTEDBARRIERS_LEVEL,
  CHARACTER_SKILLS_MAGICSKILLS_MAGICGUARDIANBEAM_LEVEL,
  CHARACTER_SKILLS_SURVIVALSKILLS_PLAYDEAD_LEVEL,
  CHARACTER_SKILLS_SURVIVALSKILLS_EXPGAINUP_LEVEL,
  CHARACTER_SKILLS_SURVIVALSKILLS_DROPRATEUP_LEVEL,
  CHARACTER_SKILLS_SURVIVALSKILLS_SAFEREST_LEVEL,
  CHARACTER_SKILLS_SURVIVALSKILLS_HPBOOST_LEVEL,
  CHARACTER_SKILLS_SURVIVALSKILLS_FIGHTERSHIGH_LEVEL,
  CHARACTER_SKILLS_SURVIVALSKILLS_SHORTREST_LEVEL,
  CHARACTER_SKILLS_SURVIVALSKILLS_MPBOOST_LEVEL,
  CHARACTER_SKILLS_SURVIVALSKILLS_SOBERANALYSIS_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_FIRSTAID_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_MINIHEAL_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_RECOVERY_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_SANCTUARY_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_HEAL_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_LIFERECOVERY_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_BRAVEAURA_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_BRAVEAURA_ISACTIVE,
  CHARACTER_SKILLS_SUPPORTSKILLS_HIGHCYCLE_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_HIGHCYCLE_ISACTIVE,
  CHARACTER_SKILLS_SUPPORTSKILLS_QUICKMOTION_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_QUICKMOTION_ISACTIVE,
  CHARACTER_SKILLS_SUPPORTSKILLS_MANARECHARGE_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_MANARECHARGE_ISACTIVE,
  CHARACTER_SKILLS_SUPPORTSKILLS_MAGICBARRIER_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_MAGICBARRIER_ISACTIVE,
  CHARACTER_SKILLS_SUPPORTSKILLS_IMMUNITY_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_IMMUNITY_ISACTIVE,
  CHARACTER_SKILLS_SUPPORTSKILLS_FASTREACTION_LEVEL,
  CHARACTER_SKILLS_SUPPORTSKILLS_FASTREACTION_ISACTIVE,
  CHARACTER_SKILLS_BATTLESKILLS_MAGICUP_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_CONCENTRATE_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_ATTACKUP_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_WHACK_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_DEFENSEUP_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_DODGEUP_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_DESPERATERESIST_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_CRITICALUP_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_ACCURACYUP_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_INCREASEDENERGY_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_INTIMIDATINGPOWER_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_DEFENSEMASTERY_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_SPELLBURST_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_SECRETCHASEATTACK_LEVEL,
  CHARACTER_SKILLS_BATTLESKILLS_SUPERGRIP_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_ISSEN_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_PULSEBLADE_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_TRIPLETHRUST_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_TRIPLETHRUST_ISACTIVE,
  CHARACTER_SKILLS_MONONOFUSKILLS_HASSOHAPPA_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_TENRYURANSEI_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_KASUMISETSUGETSUKA_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_GARYOUTENSEI_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_SHADOWLESSSLASH_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_POMMELSTRIKE_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_MAGADACHI_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_ZANTEISETTETSU_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_BUSHIDO_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_SHUKUCHI_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_SHUKUCHI_ISACTIVE,
  CHARACTER_SKILLS_MONONOFUSKILLS_NUKIUCHISENNOSEN_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_TWOHANDED_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_MEIKYOUSHISUI_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_MEIKYOUSHISUI_ISACTIVE,
  CHARACTER_SKILLS_MONONOFUSKILLS_KAIRIKIRANSHIN_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_KAIRIKIRANSHIN_ISACTIVE,
  CHARACTER_SKILLS_MONONOFUSKILLS_DAUNTLESS_LEVEL,

  CHARACTER_SKILLS_MONONOFUSKILLS_DAUNTLESS_STACKS,
  CHARACTER_SKILLS_MONONOFUSKILLS_BOUNCINGBLADE_LEVEL,
  CHARACTER_SKILLS_MONONOFUSKILLS_BOUNCINGBLADE_ISACTIVE,
  CHARACTER_SKILLS_DUALSWORDSKILLS_DUALSWORDMASTERY_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_TWINSLASH_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_SPINNINGSLASH_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_PHANTOMSLASH_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_AERIALCUT_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_CROSSPARRY_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_CROSSPARRY_ISACTIVE,
  CHARACTER_SKILLS_DUALSWORDSKILLS_CROSSPARRYISPARRIED,
  CHARACTER_SKILLS_DUALSWORDSKILLS_CHARGINGSLASH_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_SHADOWSTEP_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_SHADOWSTEP_ISACTIVE,
  CHARACTER_SKILLS_DUALSWORDSKILLS_SHININGCROSS_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_LUNARMISFORTUNE_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_TWINBUSTERBLADE_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_TWINBUSTERBLADE_ISACTIVE,
  CHARACTER_SKILLS_DUALSWORDSKILLS_REFLEX_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_FLASHBLAST_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_FLASHBLAST_ISACTIVE,
  CHARACTER_SKILLS_DUALSWORDSKILLS_STORMREAPER_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_DUALSWORDCONTROL_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_GODSPEED_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_SABERAURA_LEVEL,
  CHARACTER_SKILLS_DUALSWORDSKILLS_CRESCENTSABER_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_MAGICWARRIORMASTERY_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_CONVERSION_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_CONVERSION_ISACTIVE,
  CHARACTER_SKILLS_MAGICBLADESKILLS_RESONANCE_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_RESONANCE_ISACTIVE,
  CHARACTER_SKILLS_MAGICBLADESKILLS_RESONANCE_ACTIVESET,
  CHARACTER_SKILLS_MAGICBLADESKILLS_ENCHANTEDSPELL_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_DUALBRINGER_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_DUALBRINGER_ISACTIVE,
  CHARACTER_SKILLS_MAGICBLADESKILLS_ETHERFLARE_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_ETHERFLARE_ISACTIVE,
  CHARACTER_SKILLS_MAGICBLADESKILLS_ELEMENTSLASH_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_ENCHANTSWORD_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_ENCHANTEDBURST_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_UNIONSWORD_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_SIPHONBARRIER_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_SIPHONBARRIER_ISACTIVE,
  CHARACTER_SKILLS_MAGICBLADESKILLS_TELEPORT_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_SIPHONRECALL_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_FLOATDASH_LEVEL,
  CHARACTER_SKILLS_MAGICBLADESKILLS_MAGICSKIN_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_SHIELDMASTERY_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_SHIELDBASH_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_SHIELDCANNON_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_GUARDSTRIKE_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_FORCESHIELD_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_MAGICALSHIELD_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_SHIELDUPPERCUT_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_DUALSHIELDS_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_SHIELDREPAIR_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_BELAGERUNG_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_PROTECTION_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_PROTECTION_ISACTIVE,
  CHARACTER_SKILLS_SHIELDSKILLS_AEGIS_LEVEL,
  CHARACTER_SKILLS_SHIELDSKILLS_AEGIS_ISACTIVE,
  CHARACTER_SKILLS_SHIELDSKILLS_GUARDIAN_LEVEL,
  CHARACTER_SKILLS_GUARDSKILLS_HEAVYARMORMASTERY_LEVEL,
  CHARACTER_SKILLS_GUARDSKILLS_ADVANCEDGUARD_LEVEL,
  CHARACTER_SKILLS_GUARDSKILLS_PHYSICALGUARD_LEVEL,
  CHARACTER_SKILLS_GUARDSKILLS_LIGHTARMORMASTERY_LEVEL,
  CHARACTER_SKILLS_GUARDSKILLS_ADVANCEDEVASION_LEVEL,
  CHARACTER_SKILLS_GUARDSKILLS_MIRAGEEVASION_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_FLASHSTAB_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_CANNONSPEAR_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_DRAGONTAIL_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_DIVEIMPACT_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_DRAGONTOOTH_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_DRACONICCHARGE_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_DEADLYSPEAR_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_PUNISHRAY_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_STRIKESTAB_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_CHRONOSDIVINE_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_INFINITEDIMENSION_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_HALBERDMASTERY_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_CRITICALSPEAR_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_TORNADOLANCE_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_QUICKAURA_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_QUICKAURA_ISACTIVE,
  CHARACTER_SKILLS_HALBERDSKILLS_WARCRYOFSTRUGGLE_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_GODSPEEDWIELD_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_GODSPEEDWIELD_ISACTIVE,
  CHARACTER_SKILLS_HALBERDSKILLS_GODSPEEDWIELD_STACKS,
  CHARACTER_SKILLS_HALBERDSKILLS_ALMIGHTYWIELD_LEVEL,
  CHARACTER_SKILLS_HALBERDSKILLS_BUSTERLANCE_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_SMASH_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_BASH_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_SHELLBREAK_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_HEAVYSMASH_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_CHARIOT_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_ABSTRACTARMS_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_SONICWAVE_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_EARTHBIND_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_TRIPLEKICK_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_RUSH_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_RUSH_ISACTIVE,
  CHARACTER_SKILLS_MARTIALSKILLS_ASURAAURA_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_ASURAAURA_ISACTIVE,
  CHARACTER_SKILLS_MARTIALSKILLS_FLASHBLINK_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_MARTIALMASTERY_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_MARTIALDISCIPLINE_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_CHAKRA_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_CHAKRA_ISACTIVE,
  CHARACTER_SKILLS_MARTIALSKILLS_ENERGYCONTROL_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_ENERGYCONTROL_ISACTIVE,
  CHARACTER_SKILLS_MARTIALSKILLS_AGGRAVATE_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_STRONGCHASEATTACK_LEVEL,
  CHARACTER_SKILLS_MARTIALSKILLS_SLIDE_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_UNARMEDMASTERY_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_QICHARGE_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_LIONRAGE_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_ULTIMALIONRAGE_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_RAVINGSTORM_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_ULTIMARAVINGSTORM_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_INTERNALELIXIR_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_CLASHOFENMITY_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_MIRACLECOMEBACK_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_ULTIMAQICHARGE_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_HIDDENTALENT_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_EARTHSHAKER_LEVEL,
  CHARACTER_SKILLS_BAREHANDSKILLS_EARTHSHAKER_ISACTIVE,
  CHARACTER_SKILLS_HUNTERSKILLS_KICK_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_SUNRISEARROW_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_MAGICARROW_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_MAGICARROW_ISACTIVE,
  CHARACTER_SKILLS_HUNTERSKILLS_SATELLITEARROW_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_SLEEPTRAP_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_BEARTRAP_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_LANDMINE_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_DARKTRAP_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_HOMINGSHOT_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_DETECTION_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_DETECTION_ISACTIVE,
  CHARACTER_SKILLS_HUNTERSKILLS_CYCLONEARROW_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_VERTICALAIR_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_HUNTERBOWGUN_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_MULTIPLEHUNT_LEVEL,
  CHARACTER_SKILLS_HUNTERSKILLS_MULTIPLEHUNT_ISACTIVE,
  CHARACTER_SKILLS_NINJASKILLS_NINJUTSU_LEVEL,
  CHARACTER_SKILLS_NINJASKILLS_NINJASPIRIT_LEVEL,
  CHARACTER_SKILLS_NINJASKILLS_NINJUTSUDRILLI_LEVEL,
  CHARACTER_SKILLS_NINJASKILLS_NINJUTSUDRILLII_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_FAMILIA_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_FAMILIA_ISACTIVE,
  CHARACTER_SKILLS_WIZARDSKILLS_LIGHTNING_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_BLIZZARD_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_METEORSTRIKE_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_IMPERIALRAY_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_MANACRYSTAL_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_STONEBARRIER_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_ADVANCEDFAMILIA_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_ADVANCEDFAMILIA_ISACTIVE,
  CHARACTER_SKILLS_WIZARDSKILLS_CASTMASTERY_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_CRYSTALLASER_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_OVERLIMIT_LEVEL,
  CHARACTER_SKILLS_WIZARDSKILLS_OVERLIMIT_ISACTIVE,
  CHARACTER_SKILLS_WIZARDSKILLS_SORCERYGUIDE_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_BLESS_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_GLORIA_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_ENHANCEDBLESS_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_ROYALHEAL_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_HOLYFIST_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_HOLYLIGHT_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_ETHERBARRIER_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_ETHERBARRIER_ISACTIVE,
  CHARACTER_SKILLS_PRIESTSKILLS_PRAYER_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_PRAYER_ISACTIVE,
  CHARACTER_SKILLS_PRIESTSKILLS_STAFFTHRUST_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_EXORCISM_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_HOLYBOOK_LEVEL,
  CHARACTER_SKILLS_PRIESTSKILLS_HOLYBOOK_ISACTIVE,
  CHARACTER_SKILLS_PRIESTSKILLS_NEMESIS_LEVEL,

  CHARACTER_AILMENTS_WEAKEN_ISACTIVE,
  CHARACTER_AILMENTS_FLINCH_ISACTIVE,
  CHARACTER_AILMENTS_TUMBLE_ISACTIVE,
  CHARACTER_AILMENTS_STUN_ISACTIVE,
  CHARACTER_AILMENTS_KNOCKBACK_ISACTIVE,
  CHARACTER_AILMENTS_POISON_ISACTIVE,
  CHARACTER_AILMENTS_PARALYSIS_ISACTIVE,
  CHARACTER_AILMENTS_BLINDNESS_ISACTIVE,
  CHARACTER_AILMENTS_IGNITION_ISACTIVE,
  CHARACTER_AILMENTS_FREEZE_ISACTIVE,
  CHARACTER_AILMENTS_ARMORBREAK_ISACTIVE,
  CHARACTER_AILMENTS_SLOW_ISACTIVE,
  CHARACTER_AILMENTS_STOP_ISACTIVE,
  CHARACTER_AILMENTS_FEAR_ISACTIVE,
  CHARACTER_AILMENTS_DIZZY_ISACTIVE,
  CHARACTER_AILMENTS_LETHARGY_ISACTIVE,
  CHARACTER_AILMENTS_SILENCE_ISACTIVE,
  CHARACTER_AILMENTS_BLEED_ISACTIVE,
  CHARACTER_AILMENTS_FATIGUE_ISACTIVE,
  CHARACTER_AILMENTS_DAZZLED_ISACTIVE,

  CHARACTER_CONSUMABLES,
  CHARACTER_FOODBUFFS,

  CHARACTER_REGISLETS_ZEROSTANCE_LEVEL,
  CHARACTER_REGISLETS_MAXHPBOOST_LEVEL,
  CHARACTER_REGISLETS_MAXMPBOOST_LEVEL,
  CHARACTER_REGISLETS_MAGICATTACKBOOST_LEVEL,
  CHARACTER_REGISLETS_PHYSICALATTACKBOOST_LEVEL,
  CHARACTER_REGISLETS_MAGICDEFENSEBOOST_LEVEL,
  CHARACTER_REGISLETS_PHYSICALDEFENSEBOOST_LEVEL,
  CHARACTER_REGISLETS_ATTACKSPEEDBOOST_LEVEL,
  CHARACTER_REGISLETS_MAGICSPEEDBOOST_LEVEL,
  CHARACTER_REGISLETS_DODGEBOOST_LEVEL,
  CHARACTER_REGISLETS_ACCURACYBOOST_LEVEL,
  CHARACTER_REGISLETS_FOCUSRESONANCE_LEVEL,
  CHARACTER_REGISLETS_SPEEDRESONANCE_LEVEL,
  CHARACTER_REGISLETS_POWERRESONANCE_LEVEL,
}

export interface IntermediateConfig {
  [ParamId.CHARACTER_LEVEL]: number;

  [ParamId.CHARACTER_BASE_STR]: number;
  [ParamId.CHARACTER_BASE_INT]: number;
  [ParamId.CHARACTER_BASE_DEX]: number;
  [ParamId.CHARACTER_BASE_VIT]: number;
  [ParamId.CHARACTER_BASE_AGI]: number;
  [ParamId.CHARACTER_PERSONAL_STAT_ID]: PersonalStatId;
  [ParamId.CHARACTER_PERSONAL_STAT_VALUE]: number;

  [ParamId.CHARACTER_MAINWEAPON_TYPE]: MainWeaponTypeId;
  [ParamId.CHARACTER_MAINWEAPON_ATK]: number;
  [ParamId.CHARACTER_MAINWEAPON_REFINEMENT]: number;
  [ParamId.CHARACTER_MAINWEAPON_STABILITY]: number;
  [ParamId.CHARACTER_MAINWEAPON_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_MAINWEAPON_CRYSTAL1_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_MAINWEAPON_CRYSTAL2_STATMAP]: StatMapBuilder;

  [ParamId.CHARACTER_SUBWEAPON_TYPE]: SubWeaponTypeId;
  [ParamId.CHARACTER_SUBWEAPON_ATK]: number;
  [ParamId.CHARACTER_SUBWEAPON_DEF]: number;
  [ParamId.CHARACTER_SUBWEAPON_REFINEMENT]: number;
  [ParamId.CHARACTER_SUBWEAPON_STABILITY]: number;
  [ParamId.CHARACTER_SUBWEAPON_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_SUBWEAPON_CRYSTAL1_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_SUBWEAPON_CRYSTAL2_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_SUBWEAPON_SCROLL_CAST_TIME_REDUCTION]: number;
  [ParamId.CHARACTER_SUBWEAPON_SCROLL_MP_REDUCTION]: number;

  [ParamId.CHARACTER_ARMOR_DEF]: number;
  [ParamId.CHARACTER_ARMOR_REFINEMENT]: number;
  [ParamId.CHARACTER_ARMOR_TYPE]: ArmorTypeId;
  [ParamId.CHARACTER_ARMOR_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_ARMOR_CRYSTAL1_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_ARMOR_CRYSTAL2_STATMAP]: StatMapBuilder;

  [ParamId.CHARACTER_ADDITIONAL_GEAR_DEF]: number;
  [ParamId.CHARACTER_ADDITIONAL_GEAR_REFINEMENT]: number;
  [ParamId.CHARACTER_ADDITIONAL_GEAR_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_ADDITIONAL_GEAR_CRYSTAL1_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_ADDITIONAL_GEAR_CRYSTAL2_STATMAP]: StatMapBuilder;

  [ParamId.CHARACTER_SPECIAL_GEAR_DEF]: number;
  [ParamId.CHARACTER_SPECIAL_GEAR_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_SPECIAL_GEAR_CRYSTAL1_STATMAP]: StatMapBuilder;
  [ParamId.CHARACTER_SPECIAL_GEAR_CRYSTAL2_STATMAP]: StatMapBuilder;

  [ParamId.CHARACTER_SKILLS_BLADESKILLS_HARDHIT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_ASTUTE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_TRIGGERSLASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_TRIGGERSLASH_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_RAMPAGE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_RAMPAGE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_METEORBREAKER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_SHUTOUT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_LUNARSLASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_SONICBLADE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_SPIRALAIR_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_SWORDTEMPEST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_BUSTERBLADE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_BUSTERBLADE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_AURABLADE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_SWORDMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_QUICKSLASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_SWORDTECHNIQUES_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_WARCRY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_WARCRY_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_BERSERK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_BERSERK_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_GLADIATE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BLADESKILLS_SWIFTATTACK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_POWERSHOT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_BULLSEYE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_ARROWRAIN_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_SNIPE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_CROSSFIRE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_VANQUISHER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_TWINSTORM_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_TWINSTORM_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_TWINSTORM_ONCOOLDOWN]: boolean;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_RETROGRADESHOT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_MOEBASHOT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_PARALYSISSHOT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_SMOKEDUST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_ARMBREAK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_PARABOLACANNON_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_SHOTMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_SAMURAIARCHERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_SAMURAIARCHERY_STACKS]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_SNEAKATTACK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_LONGRANGE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_QUICKDRAW_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_DECOYSHOT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHOTSKILLS_FATALSHOT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICARROWS_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICJAVELIN_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICLANCES_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICIMPACT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICFINALE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_CHRONOSSHIFT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICWALL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICBLAST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICSTORM_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICBURST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICCANNON_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICCRASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICKNIFE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_QADAL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_QADAL_BURDEN]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_QADAL_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_QADAL_COMBAT_TIME]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MPCHARGE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_CHAINCAST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_CHAINCAST_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_CHAINCAST_STACKS]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_POWERWAVE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAXIMIZER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_RAPIDCHARGE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_RAPIDCHARGE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_RAPIDCHARGE_AMOUNTMPRECOVEREDFROMMAXIMIZER]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_ENCHANTEDBARRIERS_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICSKILLS_MAGICGUARDIANBEAM_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SURVIVALSKILLS_PLAYDEAD_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SURVIVALSKILLS_EXPGAINUP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SURVIVALSKILLS_DROPRATEUP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SURVIVALSKILLS_SAFEREST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SURVIVALSKILLS_HPBOOST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SURVIVALSKILLS_FIGHTERSHIGH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SURVIVALSKILLS_SHORTREST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SURVIVALSKILLS_MPBOOST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SURVIVALSKILLS_SOBERANALYSIS_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_FIRSTAID_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_MINIHEAL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_RECOVERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_SANCTUARY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_HEAL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_LIFERECOVERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_BRAVEAURA_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_BRAVEAURA_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_HIGHCYCLE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_HIGHCYCLE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_QUICKMOTION_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_QUICKMOTION_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_MANARECHARGE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_MANARECHARGE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_MAGICBARRIER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_MAGICBARRIER_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_IMMUNITY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_IMMUNITY_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_FASTREACTION_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SUPPORTSKILLS_FASTREACTION_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_MAGICUP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_CONCENTRATE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_ATTACKUP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_WHACK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_DEFENSEUP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_DODGEUP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_DESPERATERESIST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_CRITICALUP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_ACCURACYUP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_INCREASEDENERGY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_INTIMIDATINGPOWER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_DEFENSEMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_SPELLBURST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_SECRETCHASEATTACK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BATTLESKILLS_SUPERGRIP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_ISSEN_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_PULSEBLADE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_TRIPLETHRUST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_TRIPLETHRUST_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_HASSOHAPPA_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_TENRYURANSEI_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_KASUMISETSUGETSUKA_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_GARYOUTENSEI_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_SHADOWLESSSLASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_POMMELSTRIKE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_MAGADACHI_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_ZANTEISETTETSU_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_BUSHIDO_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_SHUKUCHI_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_SHUKUCHI_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_NUKIUCHISENNOSEN_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_TWOHANDED_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_MEIKYOUSHISUI_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_MEIKYOUSHISUI_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_KAIRIKIRANSHIN_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_KAIRIKIRANSHIN_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_DAUNTLESS_LEVEL]: number;

  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_DAUNTLESS_STACKS]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_BOUNCINGBLADE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MONONOFUSKILLS_BOUNCINGBLADE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_DUALSWORDMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_TWINSLASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_SPINNINGSLASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_PHANTOMSLASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_AERIALCUT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_CROSSPARRY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_CROSSPARRY_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_CROSSPARRYISPARRIED]: boolean;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_CHARGINGSLASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_SHADOWSTEP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_SHADOWSTEP_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_SHININGCROSS_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_LUNARMISFORTUNE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_TWINBUSTERBLADE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_TWINBUSTERBLADE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_REFLEX_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_FLASHBLAST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_FLASHBLAST_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_STORMREAPER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_DUALSWORDCONTROL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_GODSPEED_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_SABERAURA_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_DUALSWORDSKILLS_CRESCENTSABER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_MAGICWARRIORMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_CONVERSION_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_CONVERSION_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_RESONANCE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_RESONANCE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_RESONANCE_ACTIVESET]: ResonanceSetId;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_ENCHANTEDSPELL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_DUALBRINGER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_DUALBRINGER_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_ETHERFLARE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_ETHERFLARE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_ELEMENTSLASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_ENCHANTSWORD_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_ENCHANTEDBURST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_UNIONSWORD_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_SIPHONBARRIER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_SIPHONBARRIER_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_TELEPORT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_SIPHONRECALL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_FLOATDASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MAGICBLADESKILLS_MAGICSKIN_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_SHIELDMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_SHIELDBASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_SHIELDCANNON_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_GUARDSTRIKE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_FORCESHIELD_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_MAGICALSHIELD_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_SHIELDUPPERCUT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_DUALSHIELDS_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_SHIELDREPAIR_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_BELAGERUNG_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_PROTECTION_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_PROTECTION_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_AEGIS_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_AEGIS_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_SHIELDSKILLS_GUARDIAN_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_GUARDSKILLS_HEAVYARMORMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_GUARDSKILLS_ADVANCEDGUARD_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_GUARDSKILLS_PHYSICALGUARD_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_GUARDSKILLS_LIGHTARMORMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_GUARDSKILLS_ADVANCEDEVASION_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_GUARDSKILLS_MIRAGEEVASION_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_FLASHSTAB_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_CANNONSPEAR_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_DRAGONTAIL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_DIVEIMPACT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_DRAGONTOOTH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_DRACONICCHARGE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_DEADLYSPEAR_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_PUNISHRAY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_STRIKESTAB_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_CHRONOSDIVINE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_INFINITEDIMENSION_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_HALBERDMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_CRITICALSPEAR_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_TORNADOLANCE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_QUICKAURA_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_QUICKAURA_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_WARCRYOFSTRUGGLE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_GODSPEEDWIELD_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_GODSPEEDWIELD_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_GODSPEEDWIELD_STACKS]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_ALMIGHTYWIELD_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HALBERDSKILLS_BUSTERLANCE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_SMASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_BASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_SHELLBREAK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_HEAVYSMASH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_CHARIOT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_ABSTRACTARMS_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_SONICWAVE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_EARTHBIND_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_TRIPLEKICK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_RUSH_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_RUSH_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_ASURAAURA_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_ASURAAURA_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_FLASHBLINK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_MARTIALMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_MARTIALDISCIPLINE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_CHAKRA_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_CHAKRA_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_ENERGYCONTROL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_ENERGYCONTROL_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_AGGRAVATE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_STRONGCHASEATTACK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_MARTIALSKILLS_SLIDE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_UNARMEDMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_QICHARGE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_LIONRAGE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_ULTIMALIONRAGE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_RAVINGSTORM_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_ULTIMARAVINGSTORM_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_INTERNALELIXIR_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_CLASHOFENMITY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_MIRACLECOMEBACK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_ULTIMAQICHARGE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_HIDDENTALENT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_EARTHSHAKER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_BAREHANDSKILLS_EARTHSHAKER_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_KICK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_SUNRISEARROW_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_MAGICARROW_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_MAGICARROW_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_SATELLITEARROW_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_SLEEPTRAP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_BEARTRAP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_LANDMINE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_DARKTRAP_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_HOMINGSHOT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_DETECTION_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_DETECTION_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_CYCLONEARROW_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_VERTICALAIR_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_HUNTERBOWGUN_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_MULTIPLEHUNT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_HUNTERSKILLS_MULTIPLEHUNT_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_NINJASKILLS_NINJUTSU_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_NINJASKILLS_NINJASPIRIT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_NINJASKILLS_NINJUTSUDRILLI_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_NINJASKILLS_NINJUTSUDRILLII_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_FAMILIA_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_FAMILIA_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_LIGHTNING_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_BLIZZARD_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_METEORSTRIKE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_IMPERIALRAY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_MANACRYSTAL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_STONEBARRIER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_ADVANCEDFAMILIA_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_ADVANCEDFAMILIA_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_CASTMASTERY_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_CRYSTALLASER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_OVERLIMIT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_OVERLIMIT_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_WIZARDSKILLS_SORCERYGUIDE_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_BLESS_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_GLORIA_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_ENHANCEDBLESS_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_ROYALHEAL_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_HOLYFIST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_HOLYLIGHT_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_ETHERBARRIER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_ETHERBARRIER_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_PRAYER_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_PRAYER_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_STAFFTHRUST_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_EXORCISM_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_HOLYBOOK_LEVEL]: number;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_HOLYBOOK_ISACTIVE]: boolean;
  [ParamId.CHARACTER_SKILLS_PRIESTSKILLS_NEMESIS_LEVEL]: number;

  [ParamId.CHARACTER_CONSUMABLES]: Stat[]; // statmap for now
  [ParamId.CHARACTER_FOODBUFFS]: Stat[]; // statmap for now

  [ParamId.CHARACTER_AILMENTS_WEAKEN_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_FLINCH_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_TUMBLE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_STUN_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_KNOCKBACK_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_POISON_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_PARALYSIS_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_BLINDNESS_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_IGNITION_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_FREEZE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_ARMORBREAK_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_SLOW_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_STOP_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_FEAR_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_DIZZY_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_LETHARGY_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_SILENCE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_BLEED_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_FATIGUE_ISACTIVE]: boolean;
  [ParamId.CHARACTER_AILMENTS_DAZZLED_ISACTIVE]: boolean;

  [ParamId.CHARACTER_REGISLETS_ZEROSTANCE_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_MAXHPBOOST_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_MAXMPBOOST_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_MAGICATTACKBOOST_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_PHYSICALATTACKBOOST_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_MAGICDEFENSEBOOST_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_PHYSICALDEFENSEBOOST_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_ATTACKSPEEDBOOST_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_MAGICSPEEDBOOST_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_DODGEBOOST_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_ACCURACYBOOST_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_FOCUSRESONANCE_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_SPEEDRESONANCE_LEVEL]: number;
  [ParamId.CHARACTER_REGISLETS_POWERRESONANCE_LEVEL]: number;
}
