import {
  DeclarationMap,
  RecursivePartial,
  Stat,
  SubweaponType,
  WeaponType,
} from "./types";

// credits to purescript Prim.Row.Union module
export function merge<R1 extends object, R2 extends object>(
  r1: R1,
  r2: R2,
): R1 & R2 {
  var copy: any = {};
  for (var k1 in r2) {
    if ({}.hasOwnProperty.call(r2, k1)) {
      copy[k1] = r2[k1];
    }
  }
  for (var k2 in r1) {
    if ({}.hasOwnProperty.call(r1, k2)) {
      copy[k2] = r1[k2];
    }
  }
  return copy;
}

export const F = <T>(_: T) => ({
  value: _,
  map: <N>(f: (_: T) => N) => F(f(_)),
});

export const isUsingStatAccessibleSubWeapon = (d: DeclarationMap) =>
  d.characterSubweaponType === "arrow" ||
  d.characterSubweaponType === "dagger" ||
  d.characterSubweaponType === "ninjutsu-scroll" ||
  d.characterSubweaponType === "shield";

export const flattenedStats = (d: DeclarationMap): Stat[] =>
  ([] as Stat[])
    .concat(d.characterWeaponStats(d))
    .concat(
      d.characterWeaponCrystals.reduce(
        (arr, next) => arr.concat(next(d)),
        [] as Stat[],
      ),
    )
    .concat(
      isUsingStatAccessibleSubWeapon(d) ?
        d.characterSubweaponStats(d)
      : [],
    )
    .concat(
      isUsingStatAccessibleSubWeapon(d) ?
        d.characterSubweaponCrystals.reduce(
          (arr, next) => arr.concat(next(d)),
          [] as Stat[],
        )
      : [],
    )
    .concat(d.characterArmorStats(d))
    .concat(
      d.characterArmorCrystals.reduce(
        (arr, next) => arr.concat(next(d)),
        [] as Stat[],
      ),
    )
    .concat(d.characterAdditionalGearStats(d))
    .concat(
      d.characterAdditionalGearCrystals.reduce(
        (arr, next) => arr.concat(next(d)),
        [] as Stat[],
      ),
    )
    .concat(d.characterSpecialGearStats(d))
    .concat(
      d.characterSpecialGearCrystals.reduce(
        (arr, next) => arr.concat(next(d)),
        [] as Stat[],
      ),
    )
    .concat(d.characterConsumables)
    .concat(d.characterFoodBuffs);

//

export const finalize = (base: number, percent: number, flat: number) =>
  Math.floor(base * (1 + percent / 100) + flat);

// ds

export const isUsingDualSwords = <
  O extends {
    totalDualSwordSkillDualSwordMasteryLevel: number;
    weaponType: WeaponType;
    subweaponType: SubweaponType;
  },
>(
  entity: O,
) =>
  entity.weaponType === "one-handed-sword" &&
  entity.subweaponType === "one-handed-sword" &&
  entity.totalDualSwordSkillDualSwordMasteryLevel >= 1;

//

export const defaultDeclarationMap: DeclarationMap = {
  characterLevel: 0,
  characterSTR: 0,
  characterDEX: 0,
  characterINT: 0,
  characterVIT: 0,
  characterAGI: 0,
  characterPersonalStat: "none",
  characterPersonalStatPoints: 0,
  characterWeaponType: "bare-hand",
  characterWeaponATK: 0,
  characterWeaponrefinement: 0,
  characterWeaponStability: 0,
  characterWeaponStats: (_) => [],
  characterWeaponCrystals: [],
  characterSubweaponType: "none",
  characterSubweaponATK: 0,
  characterSubweaponDEF: 0,
  characterSubweaponRefinement: 0,
  characterSubweaponStability: 0,
  characterSubweaponStats: (_) => [],
  characterSubweaponCrystals: [],
  characterSubweaponScrollCastTimeReduction: 0,
  characterSubweaponScrollMPReduction: 0,
  characterArmorDEF: 0,
  characterArmorRefinement: 0,
  characterArmorType: "none",
  characterArmorStats: (_) => [],
  characterArmorCrystals: [],
  characterAdditionalGearDEF: 0,
  characterAdditionalGearRefinement: 0,
  characterAdditionalGearStats: (_) => [],
  characterAdditionalGearCrystals: [],
  characterSpecialGearDEF: 0,
  characterSpecialGearStats: (_) => [],
  characterSpecialGearCrystals: [],
  characterSkillsBladeSkillsHardHitLevel: 0,
  characterSkillsBladeSkillsAstuteLevel: 0,
  characterSkillsBladeSkillsTriggerSlashLevel: 0,
  characterSkillsBladeSkillsTriggerSlashBuffIsActive: false,
  characterSkillsBladeSkillsRampageLevel: 0,
  characterSkillsBladeSkillsRampageBuffIsActive: false,
  characterSkillsBladeSkillsMeteorBreakerLevel: 0,
  characterSkillsBladeSkillsShutOutLevel: 0,
  characterSkillsBladeSkillsLunarSlashLevel: 0,
  characterSkillsBladeSkillsSonicBladeLevel: 0,
  characterSkillsBladeSkillsSpiralAirLevel: 0,
  characterSkillsBladeSkillsSwordTempestLevel: 0,
  characterSkillsBladeSkillsBusterBladeLevel: 0,
  characterSkillsBladeSkillsBusterBladeBuffIsActive: false,
  characterSkillsBladeSkillsAuraBladeLevel: 0,
  characterSkillsBladeSkillsSwordMasteryLevel: 0,
  characterSkillsBladeSkillsQuickSlashLevel: 0,
  characterSkillsBladeSkillsSwordTechniquesLevel: 0,
  characterSkillsBladeSkillsWarCryLevel: 0,
  characterSkillsBladeSkillsWarCryBuffIsActive: false,
  characterSkillsBladeSkillsBerserkLevel: 0,
  characterSkillsBladeSkillsBerserkBuffIsActive: false,
  characterSkillsBladeSkillsGladiateLevel: 0,
  characterSkillsBladeSkillsSwiftAttackLevel: 0,

  characterSkillsShotSkillsPowerShotLevel: 0,
  characterSkillsShotSkillsBullseyeLevel: 0,
  characterSkillsShotSkillsArrowRainLevel: 0,
  characterSkillsShotSkillsSnipeLevel: 0,
  characterSkillsShotSkillsCrossFireLevel: 0,
  characterSkillsShotSkillsVanquisherLevel: 0,
  characterSkillsShotSkillsTwinStormLevel: 0,
  characterSkillsShotSkillsTwinStormBuffIsActive: false,
  characterSkillsShotSkillsTwinStormBuffOnCooldown: false,
  characterSkillsShotSkillsRetrogradeShotLevel: 0,
  characterSkillsShotSkillsMoebaShotLevel: 0,
  characterSkillsShotSkillsParalysisShotLevel: 0,
  characterSkillsShotSkillsSmokeDustLevel: 0,
  characterSkillsShotSkillsArmBreakLevel: 0,
  characterSkillsShotSkillsParabolaCannonLevel: 0,
  characterSkillsShotSkillsShotMasteryLevel: 0,
  characterSkillsShotSkillsSamuraiArcheryLevel: 0,
  characterSkillsShotSkillsSamuraiArcheryBuffIsActive: false,
  characterSkillsShotSkillsSamuraiArcheryBuffStacks: false,
  characterSkillsShotSkillsSneakAttackLevel: 0,
  characterSkillsShotSkillsLongRangeLevel: 0,
  characterSkillsShotSkillsQuickDrawLevel: 0,
  characterSkillsShotSkillsDecoyShotLevel: 0,
  characterSkillsShotSkillsFatalShotLevel: 0,

  characterSkillsMagicSkillsMagicArrowsLevel: 0,
  characterSkillsMagicSkillsMagicJavelinLevel: 0,
  characterSkillsMagicSkillsMagicLancesLevel: 0,
  characterSkillsMagicSkillsMagicImpactLevel: 0,
  characterSkillsMagicSkillsMagicFinaleLevel: 0,
  characterSkillsMagicSkillsChronosShiftLevel: 0,
  characterSkillsMagicSkillsMagicWallLevel: 0,
  characterSkillsMagicSkillsMagicBlastLevel: 0,
  characterSkillsMagicSkillsMagicStormLevel: 0,
  characterSkillsMagicSkillsMagicBurstLevel: 0,
  characterSkillsMagicSkillsMagicCannonLevel: 0,
  characterSkillsMagicSkillsMagicCrashLevel: 0,
  characterSkillsMagicSkillsMagicMasteryLevel: 0,
  characterSkillsMagicSkillsMagicKnifeLevel: 0,
  characterSkillsMagicSkillsQadalLevel: 0,
  characterSkillsMagicSkillsQadalCharge: 0,
  characterSkillsMagicSkillsQadalBuffIsActive: false,
  characterSkillsMagicSkillsQadalBuffTimer: 0,
  characterSkillsMagicSkillsMPChargeLevel: 0,
  characterSkillsMagicSkillsChainCastLevel: 0,
  characterSkillsMagicSkillsChainCastBuffIsActive: false,
  characterSkillsMagicSkillsChainCastBuffStacks: 0,
  characterSkillsMagicSkillsPowerWaveLevel: 0,
  characterSkillsMagicSkillsMaximizerLevel: 0,
  characterSkillsMagicSkillsRapidChargeLevel: 0,
  characterSkillsMagicSkillsRapidChargeBuffIsActive: false,
  characterSkillsMagicSkillsRapidChargeBuffRecoveredMPFromMaximizer: false,
  characterSkillsMagicSkillsEnchantedBarriersLevel: 0,
  characterSkillsMagicSkillsMagicGuardianBeamLevel: 0,

  characterSkillsSurvivalSkillsPlayDeadLevel: 0,
  characterSkillsSurvivalSkillsEXPGainUPLevel: 0,
  characterSkillsSurvivalSkillsDropRateUPLevel: 0,
  characterSkillsSurvivalSkillsSafeRestLevel: 0,
  characterSkillsSurvivalSkillsHPBoostLevel: 0,
  characterSkillsSurvivalSkillsFightersHighLevel: 0,
  characterSkillsSurvivalSkillsShortRestLevel: 0,
  characterSkillsSurvivalSkillsMPBoostLevel: 0,
  characterSkillsSurvivalSkillsSoberAnalysisLevel: 0,

  characterSkillsSupportSkillsFirstAidLevel: 0,
  characterSkillsSupportSkillsMiniHealLevel: 0,
  characterSkillsSupportSkillsRecoveryLevel: 0,
  characterSkillsSupportSkillsSanctuaryLevel: 0,
  characterSkillsSupportSkillsHealLevel: 0,
  characterSkillsSupportSkillsLifeRecoveryLevel: 0,
  characterSkillsSupportSkillsBraveAuraLevel: 0,
  characterSkillsSupportSkillsBraveAuraBuffIsActive: false,
  characterSkillsSupportSkillsHighCycleLevel: 0,
  characterSkillsSupportSkillsHighCycleBuffIsActive: false,
  characterSkillsSupportSkillsQuickMotionLevel: 0,
  characterSkillsSupportSkillsQuickMotionBuffIsActive: false,
  characterSkillsSupportSkillsManaRechargeLevel: 0,
  characterSkillsSupportSkillsManaRechargeBuffIsActive: false,
  characterSkillsSupportSkillsMagicBarrierLevel: 0,
  characterSkillsSupportSkillsMagicBarrierBuffIsActive: false,
  characterSkillsSupportSkillsImmunityLevel: 0,
  characterSkillsSupportSkillsImmunityBuffIsActive: false,
  characterSkillsSupportSkillsFastReactionLevel: 0,
  characterSkillsSupportSkillsFastReactionBuffIsActive: false,

  characterSkillsBattleSkillsMagicUPLevel: 0,
  characterSkillsBattleSkillsConcentrateLevel: 0,
  characterSkillsBattleSkillsAttackUPLevel: 0,
  characterSkillsBattleSkillsWhackLevel: 0,
  characterSkillsBattleSkillsDefenseUPLevel: 0,
  characterSkillsBattleSkillsDodgeUPLevel: 0,
  characterSkillsBattleSkillsDesperateResistLevel: 0,
  characterSkillsBattleSkillsCriticalUPLevel: 0,
  characterSkillsBattleSkillsAccuracyUPLevel: 0,
  characterSkillsBattleSkillsIncreasedEnergyLevel: 0,
  characterSkillsBattleSkillsIntimidatingPowerLevel: 0,
  characterSkillsBattleSkillsDefenseMasteryLevel: 0,
  characterSkillsBattleSkillsSpellBurstLevel: 0,
  characterSkillsBattleSkillsSecretChaseAttackLevel: 0,
  characterSkillsBattleSkillsSuperGripLevel: 0,

  characterSkillsMononofuSkillsIssenLevel: 0,
  characterSkillsMononofuSkillsPulseBladeLevel: 0,
  characterSkillsMononofuSkillsTripleThrustLevel: 0,
  characterSkillsMononofuSkillsTripleThrustBuffIsActive: false,
  characterSkillsMononofuSkillsHassoHappaLevel: 0,
  characterSkillsMononofuSkillsTenryuRanseiLevel: 0,
  characterSkillsMononofuSkillsKasumisetsuGetsukaLevel: 0,
  characterSkillsMononofuSkillsGaryouTenseiLevel: 0,
  characterSkillsMononofuSkillsShadowLessSlashLevel: 0,
  characterSkillsMononofuSkillsPommelStrikeLevel: 0,
  characterSkillsMononofuSkillsMagadachiLevel: 0,
  characterSkillsMononofuSkillsZanteiSettetsuLevel: 0,
  characterSkillsMononofuSkillsBushidoLevel: 0,
  characterSkillsMononofuSkillsShukuchiLevel: 0,
  characterSkillsMononofuSkillsShukuchiBuffIsActive: false,
  characterSkillsMononofuSkillsNukiuchiSennosenLevel: 0,
  characterSkillsMononofuSkillsTwoHandedLevel: 0,
  characterSkillsMononofuSkillsMeikyouShisuiLevel: 0,
  characterSkillsMononofuSkillsMeikyouShisuiBuffIsActive: false,
  characterSkillsMononofuSkillsKairikiRanshinLevel: 0,
  characterSkillsMononofuSkillsKairikiRanshinBuffIsActive: false,
  characterSkillsMononofuSkillsDauntlessLevel: 0,
  characterSkillsMononofuSkillsDauntlessBuffIsActive: false,
  characterSkillsMononofuSkillsDauntlessBuffStacks: 0,
  characterSkillsMononofuSkillsBouncingBladeLevel: 0,
  characterSkillsMononofuSkillsBouncingBladeBuffIsActive: false,

  characterSkillsDualSwordSkillsDualSwordMasteryLevel: 0,
  characterSkillsDualSwordSkillsTwinSlashLevel: 0,
  characterSkillsDualSwordSkillsSpinningSlashLevel: 0,
  characterSkillsDualSwordSkillsPhantomSlashLevel: 0,
  characterSkillsDualSwordSkillsAerialCutLevel: 0,
  characterSkillsDualSwordSkillsCrossParryLevel: 0,
  characterSkillsDualSwordSkillsCrossParryBuffIsActive: false,
  characterSkillsDualSwordSkillsCrossParryIsParried: false,
  characterSkillsDualSwordSkillsChargingSlashLevel: 0,
  characterSkillsDualSwordSkillsShadowStepLevel: 0,
  characterSkillsDualSwordSkillsShadowStepBuffIsActive: false,
  characterSkillsDualSwordSkillsShiningCrossLevel: 0,
  characterSkillsDualSwordSkillsLunarMisfortuneLevel: 0,
  characterSkillsDualSwordSkillsTwinBusterBladeLevel: 0,
  characterSkillsDualSwordSkillsTwinBusterBladeBuffIsActive: 0,
  characterSkillsDualSwordSkillsReflexLevel: 0,
  characterSkillsDualSwordSkillsFlashBlastLevel: 0,
  characterSkillsDualSwordSkillsFlashBlastBuffIsActive: false,
  characterSkillsDualSwordSkillsStormReaperLevel: 0,
  characterSkillsDualSwordSkillsDualSwordControlLevel: 0,
  characterSkillsDualSwordSkillsGodspeedLevel: 0,
  characterSkillsDualSwordSkillsSaberAuraLevel: 0,
  characterSkillsDualSwordSkillsCrescentSaberLevel: 0,

  characterSkillsMagicBladeSkillsMagicWarriorMasteryLevel: 0,
  characterSkillsMagicBladeSkillsConversionLevel: 0,
  characterSkillsMagicBladeSkillsConversionBuffIsActive: false,
  characterSkillsMagicBladeSkillsResonanceLevel: 0,
  characterSkillsMagicBladeSkillsResonanceBuffIsActive: false,
  characterSkillsMagicBladeSkillsResonanceBuffSet: "ATK/MATK",
  characterSkillsMagicBladeSkillsEnchantedSpellLevel: 0,
  characterSkillsMagicBladeSkillsDualBringerLevel: 0,
  characterSkillsMagicBladeSkillsDualBringerBuffIsActive: false,
  characterSkillsMagicBladeSkillsEtherFlareLevel: 0,
  characterSkillsMagicBladeSkillsEtherFlareBuffIsActive: false,
  characterSkillsMagicBladeSkillsElementSlashLevel: 0,
  characterSkillsMagicBladeSkillsEnchantSwordLevel: 0,
  characterSkillsMagicBladeSkillsEnchantedBurstLevel: 0,
  characterSkillsMagicBladeSkillsUnionSwordLevel: 0,
  characterSkillsMagicBladeSkillsSiphonBarrierLevel: 0,
  characterSkillsMagicBladeSkillsSiphonBarrierBuffIsActive: false,
  characterSkillsMagicBladeSkillsTeleportLevel: 0,
  characterSkillsMagicBladeSkillsSiphonRecallLevel: 0,
  characterSkillsMagicBladeSkillsFloatDashLevel: 0,
  characterSkillsMagicBladeSkillsMagicSkinLevel: 0,

  characterSkillsShieldSkillsShieldMasteryLevel: 0,
  characterSkillsShieldSkillsShieldBashLevel: 0,
  characterSkillsShieldSkillsShieldCannonLevel: 0,
  characterSkillsShieldSkillsGuardStrikeLevel: 0,
  characterSkillsShieldSkillsForceShieldLevel: 0,
  characterSkillsShieldSkillsMagicalShieldLevel: 0,
  characterSkillsShieldSkillsShieldUppercutLevel: 0,
  characterSkillsShieldSkillsDualShieldsLevel: 0,
  characterSkillsShieldSkillsShieldRepairLevel: 0,
  characterSkillsShieldSkillsBelagerungLevel: 0,
  characterSkillsShieldSkillsProtectionLevel: 0,
  characterSkillsShieldSkillsProtectionBuffIsActive: false,
  characterSkillsShieldSkillsAegisLevel: 0,
  characterSkillsShieldSkillsAegisBuffIsActive: false,
  characterSkillsShieldSkillsGuardianLevel: 0,

  characterSkillsGuardSkillsHeavyArmorMasteryLevel: 0,
  characterSkillsGuardSkillsAdvancedGuardLevel: 0,
  characterSkillsGuardSkillsPhysicalGuardLevel: 0,
  characterSkillsGuardSkillsLightArmorMasteryLevel: 0,
  characterSkillsGuardSkillsAdvancedEvasionLevel: 0,
  characterSkillsGuardSkillsMirageEvasionLevel: 0,

  characterSkillsHalberdSkillsFlashStabLevel: 0,
  characterSkillsHalberdSkillsCannonSpearLevel: 0,
  characterSkillsHalberdSkillsDragonTailLevel: 0,
  characterSkillsHalberdSkillsDiveImpactLevel: 0,
  characterSkillsHalberdSkillsDragonToothLevel: 0,
  characterSkillsHalberdSkillsDraconicChargeLevel: 0,
  characterSkillsHalberdSkillsDeadlySpearLevel: 0,
  characterSkillsHalberdSkillsPunishRayLevel: 0,
  characterSkillsHalberdSkillsStrikeStabLevel: 0,
  characterSkillsHalberdSkillsChronosDivineLevel: 0,
  characterSkillsHalberdSkillsInfiniteDimensionLevel: 0,
  characterSkillsHalberdSkillsHalberdMasteryLevel: 0,
  characterSkillsHalberdSkillsCriticalSpearLevel: 0,
  characterSkillsHalberdSkillsTornadoLanceLevel: 0,
  characterSkillsHalberdSkillsQuickAuraLevel: 0,
  characterSkillsHalberdSkillsQuickAuraBuffIsActive: false,
  characterSkillsHalberdSkillsWarCryOfStruggleLevel: 0,
  characterSkillsHalberdSkillsGodspeedWieldLevel: 0,
  characterSkillsHalberdSkillsGodspeedWieldBuffIsActive: false,
  characterSkillsHalberdSkillsGodspeedWieldBuffStacks: 0,
  characterSkillsHalberdSkillsAlmightyWieldLevel: 0,
  characterSkillsHalberdSkillsBusterLanceLevel: 0,

  characterSkillsMartialSkillsSmashLevel: 0,
  characterSkillsMartialSkillsBashLevel: 0,
  characterSkillsMartialSkillsShellBreakLevel: 0,
  characterSkillsMartialSkillsHeavySmashLevel: 0,
  characterSkillsMartialSkillsChariotLevel: 0,
  characterSkillsMartialSkillsAbstractArmsLevel: 0,
  characterSkillsMartialSkillsSonicWaveLevel: 0,
  characterSkillsMartialSkillsEarthbindLevel: 0,
  characterSkillsMartialSkillsTripleKickLevel: 0,
  characterSkillsMartialSkillsRushLevel: 0,
  characterSkillsMartialSkillsRushBuffIsActive: false,
  characterSkillsMartialSkillsAsuraAuraLevel: 0,
  characterSkillsMartialSkillsAsuraAuraBuffIsActive: false,
  characterSkillsMartialSkillsFlashBlinkLevel: 0,
  characterSkillsMartialSkillsMartialMasteryLevel: 0,
  characterSkillsMartialSkillsMartialDisciplineLevel: 0,
  characterSkillsMartialSkillsChakraLevel: 0,
  characterSkillsMartialSkillsChakraBuffIsActive: false,
  characterSkillsMartialSkillsEnergyControlLevel: 0,
  characterSkillsMartialSkillsEnergyControlBuffIsActive: false,
  characterSkillsMartialSkillsAggravateLevel: 0,
  characterSkillsMartialSkillsStrongChaseAttackLevel: 0,
  characterSkillsMartialSkillsSlideLevel: 0,

  characterSkillsBareHandSkillsUnarmedMasteryLevel: 0,
  characterSkillsBareHandSkillsQiChargeLevel: 0,
  characterSkillsBareHandSkillsLionRageLevel: 0,
  characterSkillsBareHandSkillsUltimaLionRageLevel: 0,
  characterSkillsBareHandSkillsRavingStormLevel: 0,
  characterSkillsBareHandSkillsUltimaRavingStormLevel: 0,
  characterSkillsBareHandSkillsInternalElixirLevel: 0,
  characterSkillsBareHandSkillsClashOfEnmityLevel: 0,
  characterSkillsBareHandSkillsMiracleComebackLevel: 0,
  characterSkillsBareHandSkillsUltimaQiChargeLevel: 0,
  characterSkillsBareHandSkillsHiddenTalentLevel: 0,
  characterSkillsBareHandSkillsEarthShakerLevel: 0,
  characterSkillsBareHandSkillsEarthShakerBuffIsActive: false,

  characterSkillsHunterSkillsKickLevel: 0,
  characterSkillsHunterSkillsSunriseArrowLevel: 0,
  characterSkillsHunterSkillsMagicArrowLevel: 0,
  characterSkillsHunterSkillsMagicArrowBuffIsActive: false,
  characterSkillsHunterSkillsSatelliteArrowLevel: 0,
  characterSkillsHunterSkillsSleepTrapLevel: 0,
  characterSkillsHunterSkillsBearTrapLevel: 0,
  characterSkillsHunterSkillsLandMineLevel: 0,
  characterSkillsHunterSkillsDarkTrapLevel: 0,
  characterSkillsHunterSkillsHomingShotLevel: 0,
  characterSkillsHunterSkillsDetectionLevel: 0,
  characterSkillsHunterSkillsDetectionBuffIsActive: false,
  characterSkillsHunterSkillsCycloneArrowLevel: 0,
  characterSkillsHunterSkillsVerticalAirLevel: 0,
  characterSkillsHunterSkillsHunterBowgunLevel: 0,
  characterSkillsHunterSkillsMultipleHuntLevel: 0,
  characterSkillsHunterSkillsTripleAceShotsBuffIsActive: false,
  characterSkillsHunterSkillsWolfSniperBuffIsActive: false,

  characterSkillsNinjaSkillsNinjutsuLevel: 0,
  characterSkillsNinjaSkillsNinjaSpiritLevel: 0,
  characterSkillsNinjaSkillsNinjutsuDrillILevel: 0,
  characterSkillsNinjaSkillsNinjutsuDrillIILevel: 0,

  characterSkillsWizardSkillsFamiliaLevel: 0,
  characterSkillsWizardSkillsFamiliaBuffIsActive: false,
  characterSkillsWizardSkillsLightningLevel: 0,
  characterSkillsWizardSkillsBlizzardLevel: 0,
  characterSkillsWizardSkillsMeteorStrikeLevel: 0,
  characterSkillsWizardSkillsImperialRayLevel: 0,
  characterSkillsWizardSkillsManaCrystalLevel: 0,
  characterSkillsWizardSkillsStoneBarrierLevel: 0,
  characterSkillsWizardSkillsAdvancedFamiliaLevel: 0,
  characterSkillsWizardSkillsAdvancedFamiliaBuffIsActive: 0,
  characterSkillsWizardSkillsCastMasteryLevel: 0,
  characterSkillsWizardSkillsCrystalLaserLevel: 0,
  characterSkillsWizardSkillsOverlimitLevel: 0,
  characterSkillsWizardSkillsOverlimitBuffIsActive: false,
  characterSkillsWizardSkillsSorceryGuideLevel: 0,

  characterSkillsPriestSkillsBlessLevel: 0,
  characterSkillsPriestSkillsGloriaLevel: 0,
  characterSkillsPriestSkillsEnhancedBlessLevel: 0,
  characterSkillsPriestSkillsRoyalHealLevel: 0,
  characterSkillsPriestSkillsHolyFistLevel: 0,
  characterSkillsPriestSkillsHolyLightLevel: 0,
  characterSkillsPriestSkillsEtherBarrierLevel: 0,
  characterSkillsPriestSkillsEtherBarrierBuffIsActive: false,
  characterSkillsPriestSkillsPrayerLevel: 0,
  characterSkillsPriestSkillsPrayerBuffIsActive: false,
  characterSkillsPriestSkillsStaffThrustLevel: 0,
  characterSkillsPriestSkillsExorcismLevel: 0,
  characterSkillsPriestSkillsHolyBookLevel: 0,
  characterSkillsPriestSkillsHolyBookBuffIsActive: false,
  characterSkillsPriestSkillsNemesisLevel: 0,

  characterRegisletsZeroStanceLevel: 0,
  characterRegisletsMaxHPBoostLevel: 0,
  characterRegisletsMaxMPBoostLevel: 0,
  characterRegisletsMagicAttackBoostLevel: 0,
  characterRegisletsPhysicalAttackBoostLevel: 0,
  characterRegisletsMagicDefenseBoostLevel: 0,
  characterRegisletsPhysicalDefenseBoostLevel: 0,
  characterRegisletsAttackSpeedBoostLevel: 0,
  characterRegisletsMagicSpeedBoostLevel: 0,
  characterRegisletsDodgeBoostLevel: 0,
  characterRegisletsAccuracyBoostLevel: 0,
  characterRegisletsFocusResonanceLevel: 0,
  characterRegisletsSpeedResonanceLevel: 0,
  characterRegisletsPowerResonanceLevel: 0,

  characterConsumables: [], // statmap for now
  characterFoodBuffs: [], // statmap for now

  characterAilmentsWeakenIsActive: false,
  characterAilmentsFlinchIsActive: false,
  characterAilmentsTumbleIsActive: false,
  characterAilmentsStunIsActive: false,
  characterAilmentsKnockbackIsActive: false,
  characterAilmentsPoisonIsActive: false,
  characterAilmentsParalysisIsActive: false,
  characterAilmentsBlindnessIsActive: false,
  characterAilmentsIgnitionIsActive: false,
  characterAilmentsFreezeIsActive: false,
  characterAilmentsArmorBreakIsActive: false,
  characterAilmentsSlowIsActive: false,
  characterAilmentsStopIsActive: false,
  characterAilmentsFearIsActive: false,
  characterAilmentsDizzyIsActive: false,
  characterAilmentsLethargyIsActive: false,
  characterAilmentsSilenceIsActive: false,
  characterAilmentsBleedIsActive: false,
  characterAilmentsFatigueIsActive: false,
  characterAilmentsDazzledIsActive: false,

  // target
  targetLevel: 0,
  targetPhysicalResistance: 0,
  targetMagicResistance: 0,
  targetWeaponResistance: 0,
  targetDEF: 0,
  targetMDEF: 0,
  targetElement: "neutral",
  targetAilmentsWeakenIsActive: false,
  targetAilmentsFlinchIsActive: false,
  targetAilmentsTumbleIsActive: false,
  targetAilmentsStunIsActive: false,
  targetAilmentsKnockbackIsActive: false,
  targetAilmentsPoisonIsActive: false,
  targetAilmentsParalysisIsActive: false,
  targetAilmentsBlindnessIsActive: false,
  targetAilmentsIgnitionIsActive: false,
  targetAilmentsFreezeIsActive: false,
  targetAilmentsArmorBreakIsActive: false,
  targetAilmentsSlowIsActive: false,
  targetAilmentsStopIsActive: false,
  targetAilmentsFearIsActive: false,
  targetAilmentsDizzyIsActive: false,
  targetAilmentsLethargyIsActive: false,
  targetAilmentsSilenceIsActive: false,
  targetAilmentsBleedIsActive: false,
  targetAilmentsFatigueIsActive: false,
  targetAilmentsDazzledIsActive: false,
  targetDistanceFromPlayer: 0,
  targetProration: 0,

  // damage instance

  damageBase: 0,
  damageConstant: 0,
  damagePierce: 0,
  damageFlatUnsheatheAttack: 0,
  damageCriticalDamageModifier: 0,
  damageElementDamageModifier: 0,
  damageInnateSkillDamageModifier: 0,
  damagePercentUnsheatheAttack: 0,
  damageStability: 0,
  damageSkillDamageModifier: 0,
  damageDistanceDependentDamageModifier: 0,
  damageLastDamageModifier: 0,
  damageComboRelatedDamageModifier: 0,
  damageBaseDropGemDamageModifier: 0,
  damageUltimaLionRageDamageModifier: 0,
  damageIsGuarded: false,
  damageIsGrazed: false,
} as const;

export const createDeclarationMap = <T extends Partial<DeclarationMap>>(
  d: T,
): T & DeclarationMap => ({
  ...defaultDeclarationMap,
  ...(d as T),
});
